/// Base class for all all client-side errors that can be generated by the app
sealed class AppException implements Exception {
  const AppException(this.code, this.message);
  final String code;
  final String message;

  @override
  String toString() => message;
}

class UnknownException extends AppException {
  const UnknownException()
      : super(
          "unknown-exception",
          "Oops! Something went wrong.",
        );
}

class DataNotFoundException extends AppException {
  const DataNotFoundException()
      : super(
          "data-not-found-exception",
          "Data not found.",
        );
}
